version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778/tcp"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - deuna-network
  db:
    container_name: db_rickandmorty
    image: postgres
    environment:
      POSTGRES_DB: rickandmorty_db
      POSTGRES_PASSWORD: postgresql
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - "./db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - deuna-network
  api:
    container_name: deuna-rickandmorty-api
    build:
      context: .
    environment:
      SERVER_PORT: 8080
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      DB_HOST: db_rickandmorty
      DB_PORT: 5432
      DB_PASSWORD: postgresql
      DB_DATABASE: rickandmorty_db
      RICHANDMORTY_API_BASE_PATH: https://rickandmortyapi.com/api
    ports:
      - "8080:8080"
    networks:
      - deuna-network
    depends_on:
      - jaeger
      - db

networks:
  deuna-network: